version: '2.1'

services:

  infinispan:
    image: infinispan/server:11.0.4.Final
    container_name: infinispan
    ports:
        - 11222:11222
    command: "/opt/infinispan/bin/server.sh -c infinispan-demo.xml"
    volumes:
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan-demo.xml:z

  zookeeper:
    container_name: zookeeper
    image: strimzi/kafka:0.14.0-kafka-2.3.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: kafka
    image: strimzi/kafka:0.14.0-kafka-2.3.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "storage-topic:1:1:compact,global-id-topic:1:1:compact,input-topic:1:1:compact,logx-topic:1:1:compact,dbx-topic:1:1:compact"

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - "8280:8080"
    volumes:
      - ./keycloak/kogito-realm.json:/tmp/kogito-realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/kogito-realm.json

#  data-index:
#    container_name: data-index
#    image: quay.io/kiegroup/kogito-data-index-infinispan-nightly:latest
#    depends_on:
#      - kafka
#      - infinispan
#    ports:
#      - "8180:8180"
#    volumes:
#      - ./data-index/persistence:/home/kogito/data/protobufs
#      - ./scripts/wait-for-it.sh:/home/kogito/wait-for-it.sh
#    command: [
#        "./wait-for-it.sh", "kafka:9093", "-t", "30", "--", "./kogito-app-launch.sh"
#    ]
#    environment:
#      QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: infinispan:11222
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
#
#  task-console:
#    container_name: task-console
#    image: quay.io/kiegroup/kogito-task-console
#    ports:
#      - 8380:8380
#    depends_on:
#      - keycloak
#    volumes:
#      - ./scripts/wait-for-it.sh:/home/kogito/wait-for-it.sh
#    command: [
#        "./wait-for-it.sh", "keycloak:8280", "-t", "30", "--", "./kogito-app-launch.sh"
#    ]
#    environment:
#      HTTP_PORT: 8380
#      QUARKUS_PROFILE: "keycloak"



